// Code generated by protoc-gen-go.
// source: proto/game.proto
// DO NOT EDIT!

/*
Package game is a generated protocol buffer package.

It is generated from these files:
	proto/game.proto

It has these top-level messages:
	PingC2G
	PongG2C
	LoginC2G
	LoginG2C
*/
package game

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PingC2G struct {
	Msg string `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
}

func (m *PingC2G) Reset()                    { *m = PingC2G{} }
func (m *PingC2G) String() string            { return proto.CompactTextString(m) }
func (*PingC2G) ProtoMessage()               {}
func (*PingC2G) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PingC2G) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type PongG2C struct {
	Msg string `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
}

func (m *PongG2C) Reset()                    { *m = PongG2C{} }
func (m *PongG2C) String() string            { return proto.CompactTextString(m) }
func (*PongG2C) ProtoMessage()               {}
func (*PongG2C) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PongG2C) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type LoginC2G struct {
	Token  string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	RoleId uint32 `protobuf:"varint,2,opt,name=role_id,json=roleId" json:"role_id,omitempty"`
}

func (m *LoginC2G) Reset()                    { *m = LoginC2G{} }
func (m *LoginC2G) String() string            { return proto.CompactTextString(m) }
func (*LoginC2G) ProtoMessage()               {}
func (*LoginC2G) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *LoginC2G) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginC2G) GetRoleId() uint32 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

type LoginG2C struct {
	Result   bool   `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	RoleId   uint32 `protobuf:"varint,2,opt,name=role_id,json=roleId" json:"role_id,omitempty"`
	Rolename string `protobuf:"bytes,3,opt,name=rolename" json:"rolename,omitempty"`
	Level    uint32 `protobuf:"varint,4,opt,name=level" json:"level,omitempty"`
}

func (m *LoginG2C) Reset()                    { *m = LoginG2C{} }
func (m *LoginG2C) String() string            { return proto.CompactTextString(m) }
func (*LoginG2C) ProtoMessage()               {}
func (*LoginG2C) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *LoginG2C) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func (m *LoginG2C) GetRoleId() uint32 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

func (m *LoginG2C) GetRolename() string {
	if m != nil {
		return m.Rolename
	}
	return ""
}

func (m *LoginG2C) GetLevel() uint32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func init() {
	proto.RegisterType((*PingC2G)(nil), "game.ping_c2g")
	proto.RegisterType((*PongG2C)(nil), "game.pong_g2c")
	proto.RegisterType((*LoginC2G)(nil), "game.login_c2g")
	proto.RegisterType((*LoginG2C)(nil), "game.login_g2c")
}

func init() { proto.RegisterFile("proto/game.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 183 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0x4f, 0xcc, 0x4d, 0xd5, 0x03, 0x33, 0x85, 0x58, 0x40, 0x6c, 0x25, 0x19, 0x2e,
	0x8e, 0x82, 0xcc, 0xbc, 0xf4, 0xf8, 0x64, 0xa3, 0x74, 0x21, 0x01, 0x2e, 0xe6, 0xdc, 0xe2, 0x74,
	0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x10, 0x13, 0x2c, 0x9b, 0x9f, 0x97, 0x1e, 0x9f, 0x6e,
	0x94, 0x8c, 0x45, 0xd6, 0x8a, 0x8b, 0x33, 0x27, 0x3f, 0x3d, 0x33, 0x0f, 0xac, 0x59, 0x84, 0x8b,
	0xb5, 0x24, 0x3f, 0x3b, 0x35, 0x0f, 0xaa, 0x00, 0xc2, 0x11, 0x12, 0xe7, 0x62, 0x2f, 0xca, 0xcf,
	0x49, 0x8d, 0xcf, 0x4c, 0x91, 0x60, 0x52, 0x60, 0xd4, 0xe0, 0x0d, 0x62, 0x03, 0x71, 0x3d, 0x53,
	0x94, 0xf2, 0x60, 0x7a, 0x41, 0x46, 0x8b, 0x71, 0xb1, 0x15, 0xa5, 0x16, 0x97, 0xe6, 0x94, 0x80,
	0x35, 0x73, 0x04, 0x41, 0x79, 0x38, 0x75, 0x0b, 0x49, 0x71, 0x71, 0x80, 0x58, 0x79, 0x89, 0xb9,
	0xa9, 0x12, 0xcc, 0x60, 0xfb, 0xe0, 0x7c, 0x90, 0x43, 0x72, 0x52, 0xcb, 0x52, 0x73, 0x24, 0x58,
	0xc0, 0x5a, 0x20, 0x9c, 0x24, 0x36, 0xb0, 0xa7, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x07,
	0x7e, 0xeb, 0x4d, 0x08, 0x01, 0x00, 0x00,
}
