// Code generated by protoc-gen-go.
// source: proto/login.proto
// DO NOT EDIT!

/*
Package login is a generated protocol buffer package.

It is generated from these files:
	proto/login.proto

It has these top-level messages:
	Signin
	Signup
	SigninRet
	Ping
	Pong
*/
package login

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Signin struct {
	Token  string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	Id     int32  `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	Name   string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Passwd string `protobuf:"bytes,4,opt,name=passwd" json:"passwd,omitempty"`
	Sdkid  string `protobuf:"bytes,5,opt,name=sdkid" json:"sdkid,omitempty"`
}

func (m *Signin) Reset()                    { *m = Signin{} }
func (m *Signin) String() string            { return proto.CompactTextString(m) }
func (*Signin) ProtoMessage()               {}
func (*Signin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Signin) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Signin) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Signin) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Signin) GetPasswd() string {
	if m != nil {
		return m.Passwd
	}
	return ""
}

func (m *Signin) GetSdkid() string {
	if m != nil {
		return m.Sdkid
	}
	return ""
}

type Signup struct {
	Token  string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	Name   string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Passwd string `protobuf:"bytes,4,opt,name=passwd" json:"passwd,omitempty"`
	Sdkid  string `protobuf:"bytes,5,opt,name=sdkid" json:"sdkid,omitempty"`
}

func (m *Signup) Reset()                    { *m = Signup{} }
func (m *Signup) String() string            { return proto.CompactTextString(m) }
func (*Signup) ProtoMessage()               {}
func (*Signup) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Signup) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Signup) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Signup) GetPasswd() string {
	if m != nil {
		return m.Passwd
	}
	return ""
}

func (m *Signup) GetSdkid() string {
	if m != nil {
		return m.Sdkid
	}
	return ""
}

type SigninRet struct {
}

func (m *SigninRet) Reset()                    { *m = SigninRet{} }
func (m *SigninRet) String() string            { return proto.CompactTextString(m) }
func (*SigninRet) ProtoMessage()               {}
func (*SigninRet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type Ping struct {
	Hello string `protobuf:"bytes,1,opt,name=hello" json:"hello,omitempty"`
}

func (m *Ping) Reset()                    { *m = Ping{} }
func (m *Ping) String() string            { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()               {}
func (*Ping) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Ping) GetHello() string {
	if m != nil {
		return m.Hello
	}
	return ""
}

type Pong struct {
	Hello string `protobuf:"bytes,1,opt,name=hello" json:"hello,omitempty"`
}

func (m *Pong) Reset()                    { *m = Pong{} }
func (m *Pong) String() string            { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()               {}
func (*Pong) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Pong) GetHello() string {
	if m != nil {
		return m.Hello
	}
	return ""
}

func init() {
	proto.RegisterType((*Signin)(nil), "login.signin")
	proto.RegisterType((*Signup)(nil), "login.signup")
	proto.RegisterType((*SigninRet)(nil), "login.signin_ret")
	proto.RegisterType((*Ping)(nil), "login.ping")
	proto.RegisterType((*Pong)(nil), "login.pong")
}

func init() { proto.RegisterFile("proto/login.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 177 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x90, 0xb1, 0x0a, 0xc2, 0x30,
	0x10, 0x86, 0x69, 0x6d, 0x0a, 0x1e, 0x22, 0x18, 0x44, 0x32, 0x38, 0x94, 0x4e, 0x9d, 0x74, 0xf0,
	0x4d, 0xfa, 0x02, 0x5a, 0x49, 0xa8, 0x47, 0xeb, 0x5d, 0x68, 0x22, 0xbe, 0xbe, 0xf4, 0xa2, 0x63,
	0x27, 0xb7, 0xfb, 0x72, 0x3f, 0xff, 0x47, 0x0e, 0x76, 0x7e, 0xe2, 0xc8, 0xe7, 0x91, 0x7b, 0xa4,
	0x93, 0xcc, 0x5a, 0x09, 0xd4, 0x1e, 0xca, 0x80, 0x3d, 0x21, 0xe9, 0x3d, 0xa8, 0xc8, 0x83, 0x23,
	0x93, 0x55, 0x59, 0xb3, 0x6e, 0x13, 0xe8, 0x2d, 0xe4, 0x68, 0x4d, 0x5e, 0x65, 0x8d, 0x6a, 0x73,
	0xb4, 0x5a, 0x43, 0x41, 0xdd, 0xd3, 0x99, 0x95, 0x84, 0x64, 0xd6, 0x07, 0x28, 0x7d, 0x17, 0xc2,
	0xdb, 0x9a, 0x42, 0x5e, 0xbf, 0x34, 0x37, 0x06, 0x3b, 0xa0, 0x35, 0x2a, 0x35, 0x0a, 0xd4, 0xb7,
	0x64, 0x7c, 0xf9, 0x05, 0xe3, 0xff, 0x86, 0x0d, 0x40, 0xfa, 0xd3, 0x75, 0x72, 0xb1, 0x3e, 0x42,
	0xe1, 0x91, 0xfa, 0x39, 0xfb, 0x70, 0xe3, 0xc8, 0x3f, 0x9b, 0x80, 0x6c, 0x79, 0x69, 0x7b, 0x2f,
	0xe5, 0x56, 0x97, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xdf, 0x01, 0xe6, 0x2d, 0x40, 0x01, 0x00,
	0x00,
}
